// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OperationsColumns holds the columns for the "operations" table.
	OperationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "type", Type: field.TypeInt},
		{Name: "completed", Type: field.TypeBool, Default: false},
		{Name: "success", Type: field.TypeBool, Default: false},
		{Name: "operator", Type: field.TypeInt64},
		{Name: "message_id", Type: field.TypeInt},
		{Name: "remind_id", Type: field.TypeUUID, Nullable: true},
	}
	// OperationsTable holds the schema information for the "operations" table.
	OperationsTable = &schema.Table{
		Name:       "operations",
		Columns:    OperationsColumns,
		PrimaryKey: []*schema.Column{OperationsColumns[0]},
	}
	// RemindsColumns holds the columns for the "reminds" table.
	RemindsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "chat_id", Type: field.TypeInt64},
		{Name: "owner", Type: field.TypeInt64},
		{Name: "period", Type: field.TypeString, Nullable: true},
		{Name: "content", Type: field.TypeString, Nullable: true},
		{Name: "name", Type: field.TypeString},
	}
	// RemindsTable holds the schema information for the "reminds" table.
	RemindsTable = &schema.Table{
		Name:       "reminds",
		Columns:    RemindsColumns,
		PrimaryKey: []*schema.Column{RemindsColumns[0]},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "chat_id", Type: field.TypeInt64},
		{Name: "allow_all_user", Type: field.TypeBool},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OperationsTable,
		RemindsTable,
		SettingsTable,
	}
)

func init() {
}
