// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/google/uuid"
	"github.com/lemonnekogh/reminderbot/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/lemonnekogh/reminderbot/ent/operations"
	"github.com/lemonnekogh/reminderbot/ent/reminds"
	"github.com/lemonnekogh/reminderbot/ent/settings"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Operations is the client for interacting with the Operations builders.
	Operations *OperationsClient
	// Reminds is the client for interacting with the Reminds builders.
	Reminds *RemindsClient
	// Settings is the client for interacting with the Settings builders.
	Settings *SettingsClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Operations = NewOperationsClient(c.config)
	c.Reminds = NewRemindsClient(c.config)
	c.Settings = NewSettingsClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Operations: NewOperationsClient(cfg),
		Reminds:    NewRemindsClient(cfg),
		Settings:   NewSettingsClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Operations: NewOperationsClient(cfg),
		Reminds:    NewRemindsClient(cfg),
		Settings:   NewSettingsClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Operations.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Operations.Use(hooks...)
	c.Reminds.Use(hooks...)
	c.Settings.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Operations.Intercept(interceptors...)
	c.Reminds.Intercept(interceptors...)
	c.Settings.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *OperationsMutation:
		return c.Operations.mutate(ctx, m)
	case *RemindsMutation:
		return c.Reminds.mutate(ctx, m)
	case *SettingsMutation:
		return c.Settings.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// OperationsClient is a client for the Operations schema.
type OperationsClient struct {
	config
}

// NewOperationsClient returns a client for the Operations from the given config.
func NewOperationsClient(c config) *OperationsClient {
	return &OperationsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `operations.Hooks(f(g(h())))`.
func (c *OperationsClient) Use(hooks ...Hook) {
	c.hooks.Operations = append(c.hooks.Operations, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `operations.Intercept(f(g(h())))`.
func (c *OperationsClient) Intercept(interceptors ...Interceptor) {
	c.inters.Operations = append(c.inters.Operations, interceptors...)
}

// Create returns a builder for creating a Operations entity.
func (c *OperationsClient) Create() *OperationsCreate {
	mutation := newOperationsMutation(c.config, OpCreate)
	return &OperationsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Operations entities.
func (c *OperationsClient) CreateBulk(builders ...*OperationsCreate) *OperationsCreateBulk {
	return &OperationsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Operations.
func (c *OperationsClient) Update() *OperationsUpdate {
	mutation := newOperationsMutation(c.config, OpUpdate)
	return &OperationsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OperationsClient) UpdateOne(o *Operations) *OperationsUpdateOne {
	mutation := newOperationsMutation(c.config, OpUpdateOne, withOperations(o))
	return &OperationsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OperationsClient) UpdateOneID(id uuid.UUID) *OperationsUpdateOne {
	mutation := newOperationsMutation(c.config, OpUpdateOne, withOperationsID(id))
	return &OperationsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Operations.
func (c *OperationsClient) Delete() *OperationsDelete {
	mutation := newOperationsMutation(c.config, OpDelete)
	return &OperationsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OperationsClient) DeleteOne(o *Operations) *OperationsDeleteOne {
	return c.DeleteOneID(o.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OperationsClient) DeleteOneID(id uuid.UUID) *OperationsDeleteOne {
	builder := c.Delete().Where(operations.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OperationsDeleteOne{builder}
}

// Query returns a query builder for Operations.
func (c *OperationsClient) Query() *OperationsQuery {
	return &OperationsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOperations},
		inters: c.Interceptors(),
	}
}

// Get returns a Operations entity by its id.
func (c *OperationsClient) Get(ctx context.Context, id uuid.UUID) (*Operations, error) {
	return c.Query().Where(operations.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OperationsClient) GetX(ctx context.Context, id uuid.UUID) *Operations {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OperationsClient) Hooks() []Hook {
	return c.hooks.Operations
}

// Interceptors returns the client interceptors.
func (c *OperationsClient) Interceptors() []Interceptor {
	return c.inters.Operations
}

func (c *OperationsClient) mutate(ctx context.Context, m *OperationsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OperationsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OperationsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OperationsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OperationsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Operations mutation op: %q", m.Op())
	}
}

// RemindsClient is a client for the Reminds schema.
type RemindsClient struct {
	config
}

// NewRemindsClient returns a client for the Reminds from the given config.
func NewRemindsClient(c config) *RemindsClient {
	return &RemindsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `reminds.Hooks(f(g(h())))`.
func (c *RemindsClient) Use(hooks ...Hook) {
	c.hooks.Reminds = append(c.hooks.Reminds, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `reminds.Intercept(f(g(h())))`.
func (c *RemindsClient) Intercept(interceptors ...Interceptor) {
	c.inters.Reminds = append(c.inters.Reminds, interceptors...)
}

// Create returns a builder for creating a Reminds entity.
func (c *RemindsClient) Create() *RemindsCreate {
	mutation := newRemindsMutation(c.config, OpCreate)
	return &RemindsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Reminds entities.
func (c *RemindsClient) CreateBulk(builders ...*RemindsCreate) *RemindsCreateBulk {
	return &RemindsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Reminds.
func (c *RemindsClient) Update() *RemindsUpdate {
	mutation := newRemindsMutation(c.config, OpUpdate)
	return &RemindsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RemindsClient) UpdateOne(r *Reminds) *RemindsUpdateOne {
	mutation := newRemindsMutation(c.config, OpUpdateOne, withReminds(r))
	return &RemindsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RemindsClient) UpdateOneID(id uuid.UUID) *RemindsUpdateOne {
	mutation := newRemindsMutation(c.config, OpUpdateOne, withRemindsID(id))
	return &RemindsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Reminds.
func (c *RemindsClient) Delete() *RemindsDelete {
	mutation := newRemindsMutation(c.config, OpDelete)
	return &RemindsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RemindsClient) DeleteOne(r *Reminds) *RemindsDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RemindsClient) DeleteOneID(id uuid.UUID) *RemindsDeleteOne {
	builder := c.Delete().Where(reminds.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RemindsDeleteOne{builder}
}

// Query returns a query builder for Reminds.
func (c *RemindsClient) Query() *RemindsQuery {
	return &RemindsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeReminds},
		inters: c.Interceptors(),
	}
}

// Get returns a Reminds entity by its id.
func (c *RemindsClient) Get(ctx context.Context, id uuid.UUID) (*Reminds, error) {
	return c.Query().Where(reminds.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RemindsClient) GetX(ctx context.Context, id uuid.UUID) *Reminds {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RemindsClient) Hooks() []Hook {
	return c.hooks.Reminds
}

// Interceptors returns the client interceptors.
func (c *RemindsClient) Interceptors() []Interceptor {
	return c.inters.Reminds
}

func (c *RemindsClient) mutate(ctx context.Context, m *RemindsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RemindsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RemindsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RemindsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RemindsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Reminds mutation op: %q", m.Op())
	}
}

// SettingsClient is a client for the Settings schema.
type SettingsClient struct {
	config
}

// NewSettingsClient returns a client for the Settings from the given config.
func NewSettingsClient(c config) *SettingsClient {
	return &SettingsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `settings.Hooks(f(g(h())))`.
func (c *SettingsClient) Use(hooks ...Hook) {
	c.hooks.Settings = append(c.hooks.Settings, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `settings.Intercept(f(g(h())))`.
func (c *SettingsClient) Intercept(interceptors ...Interceptor) {
	c.inters.Settings = append(c.inters.Settings, interceptors...)
}

// Create returns a builder for creating a Settings entity.
func (c *SettingsClient) Create() *SettingsCreate {
	mutation := newSettingsMutation(c.config, OpCreate)
	return &SettingsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Settings entities.
func (c *SettingsClient) CreateBulk(builders ...*SettingsCreate) *SettingsCreateBulk {
	return &SettingsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Settings.
func (c *SettingsClient) Update() *SettingsUpdate {
	mutation := newSettingsMutation(c.config, OpUpdate)
	return &SettingsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SettingsClient) UpdateOne(s *Settings) *SettingsUpdateOne {
	mutation := newSettingsMutation(c.config, OpUpdateOne, withSettings(s))
	return &SettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SettingsClient) UpdateOneID(id int) *SettingsUpdateOne {
	mutation := newSettingsMutation(c.config, OpUpdateOne, withSettingsID(id))
	return &SettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Settings.
func (c *SettingsClient) Delete() *SettingsDelete {
	mutation := newSettingsMutation(c.config, OpDelete)
	return &SettingsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SettingsClient) DeleteOne(s *Settings) *SettingsDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SettingsClient) DeleteOneID(id int) *SettingsDeleteOne {
	builder := c.Delete().Where(settings.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SettingsDeleteOne{builder}
}

// Query returns a query builder for Settings.
func (c *SettingsClient) Query() *SettingsQuery {
	return &SettingsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSettings},
		inters: c.Interceptors(),
	}
}

// Get returns a Settings entity by its id.
func (c *SettingsClient) Get(ctx context.Context, id int) (*Settings, error) {
	return c.Query().Where(settings.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SettingsClient) GetX(ctx context.Context, id int) *Settings {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SettingsClient) Hooks() []Hook {
	return c.hooks.Settings
}

// Interceptors returns the client interceptors.
func (c *SettingsClient) Interceptors() []Interceptor {
	return c.inters.Settings
}

func (c *SettingsClient) mutate(ctx context.Context, m *SettingsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SettingsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SettingsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SettingsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Settings mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Operations, Reminds, Settings []ent.Hook
	}
	inters struct {
		Operations, Reminds, Settings []ent.Interceptor
	}
)
