// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/lemonnekogh/reminderbot/ent/operations"
	"github.com/lemonnekogh/reminderbot/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	operationsFields := schema.Operations{}.Fields()
	_ = operationsFields
	// operationsDescCompleted is the schema descriptor for completed field.
	operationsDescCompleted := operationsFields[2].Descriptor()
	// operations.DefaultCompleted holds the default value on creation for the completed field.
	operations.DefaultCompleted = operationsDescCompleted.Default.(bool)
	// operationsDescSuccess is the schema descriptor for success field.
	operationsDescSuccess := operationsFields[3].Descriptor()
	// operations.DefaultSuccess holds the default value on creation for the success field.
	operations.DefaultSuccess = operationsDescSuccess.Default.(bool)
}
