// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReminderBot.Bot.Persistence;

#nullable disable

namespace ReminderBot.Bot.Migrations
{
    [DbContext(typeof(PersistenceContext))]
    [Migration("20231123050645_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReminderBot.Bot.Persistence.Model.Operations", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean")
                        .HasColumnName("completed");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<long>("OperatorUser")
                        .HasColumnType("bigint")
                        .HasColumnName("operator_user");

                    b.Property<string>("RemindItemId")
                        .HasColumnType("text")
                        .HasColumnName("remind_item_id");

                    b.HasKey("MessageId");

                    b.ToTable("operations", "reminder_bot");
                });

            modelBuilder.Entity("ReminderBot.Bot.Persistence.Model.RemindItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("Owner")
                        .HasColumnType("bigint")
                        .HasColumnName("owner");

                    b.Property<string>("Period")
                        .HasColumnType("text")
                        .HasColumnName("period");

                    b.HasKey("Id");

                    b.ToTable("remind_items", "reminder_bot");
                });

            modelBuilder.Entity("ReminderBot.Bot.Persistence.Model.Settings", b =>
                {
                    b.Property<long>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ChatId"));

                    b.Property<bool>("AllowAllUsers")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_all_users");

                    b.HasKey("ChatId");

                    b.ToTable("settings", "reminder_bot");
                });
#pragma warning restore 612, 618
        }
    }
}
