name: PR Check
on:
  pull_request:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest
    container: rust:1.76
    steps:
      - uses: actions/checkout@v4
      - name: Test build
        run: cargo build

  unit-test:
    runs-on: ubuntu-latest
    container: rust:1.76
    services:
      postgres:
        image: postgres:15.4-alpine
        env:
          POSTGRES_DB: reminder_bot
          POSTGRES_USER: reminder_bot
          POSTGRES_PASSWORD: reminder_bot
        ports:
          - 15432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Get postgres service IP and do unit test
        run: |
          apt update && apt install dnsutils libpq-dev -y
          export DB_URL="postgresql://reminder_bot:reminder_bot@$(nslookup postgres | awk -F': ' 'NR==6 { print $2 } '):15432/reminder_bot"
          cargo test --all

  lint:
    runs-on: ubuntu-latest
    container: rust:1.76
    steps:
    - name: Format
      run: |
        cargo check --all
        if [[ $(git status --porcelain) == "" ]] then; exit 0; else exit 1; fi
    - name: Lint
      run: |
        cargo clippy --fix
        if [[ $(git status --porcelain) == "" ]] then; exit 0; else exit 1; fi
