// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Operations is the predicate function for operations builders.
type Operations func(*sql.Selector)

// Reminds is the predicate function for reminds builders.
type Reminds func(*sql.Selector)

// Settings is the predicate function for settings builders.
type Settings func(*sql.Selector)
